# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch: {}

exporters:
  clickhouse:
    endpoint: "tcp://clickhouse-server:9000"
    database: "default"
    username: "admin"
    password: "admin"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [clickhouse]

    traces:
      receivers: [otlp]
      exporters: [clickhouse]
