
services:
  slim_gateway:
    image: ghcr.io/agntcy/slim:latest
    container_name: slim_gateway
    ports:
      - "46357:46357"
    environment:
      - PASSWORD=${PASSWORD:-dummy}  # Default password if not set
    volumes:
      - ./gw/config/base/server-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]
    restart: unless-stopped
    networks:
      - slim_network  # Ensure both services are on the same network


networks:
  slim_network:
    driver: bridge
