name: Publish Python Package to Artifactory

on:
  push:
    tags:
      - 'sdk-v*'  # Trigger on version tags (e.g., sdk-v1.0.0)
      - '!sdk-v*-rc0'

    workflow_dispatch:  # Allow manual triggering of the workflow


jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install needed utilities
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create virtual environment
        run: |
          uv venv --python 3.9

      - name: Install dependencies
        run: |
          uv sync

      - name: Build package
        run: |
          make build

      - name: Import Vault Secrets
        id: import-secrets
        uses: cisco-eti/dragonfly-actions/vault@main
        with:
          method: approle
          url: ${{ vars.KEEPER_URL }}
          roleId: ${{ secrets.VAULT_ESPRESSO_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_ESPRESSO_APPROLE_SECRET_ID }}
          namespace: eticloud/apps/espresso
          secrets: |
              secret/data/artifactory.devhub-cloud.cisco.com  username       | ARTIFACTORY_USERNAME ;
              secret/data/artifactory.devhub-cloud.cisco.com  identity-token | ARTIFACTORY_PASSWORD ;

      - name: Publish to Artifactory
        env:
          TWINE_USERNAME: ${{ env.ARTIFACTORY_USERNAME }}
          TWINE_PASSWORD: ${{ env.ARTIFACTORY_PASSWORD }}
        run: |
          uv pip install twine
          source .venv/bin/activate
          python -m twine upload --repository-url https://artifactory.devhub-cloud.cisco.com/artifactory/api/pypi/outshift-pypi dist/*
