# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: python-build
on:
  workflow_call:

jobs:
  python-bindings-wheels:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          py-install: false
          poetry-install: false
          uv-install: true
      - name: Build wheel
        run: |
          uv build
      - name: Check distributions
        run: |
          uvx twine check dist/*
      - name: Upload wheel
        uses: actions/upload-artifact@v6
        with:
          name: python-distributions
          path: ./dist
